variable "private_key_path" {}
variable "public_key_path" {}
variable "ec2_user" {}
variable "xc_password" {}
variable "xc_namespace" {}
variable "xc_tenant" {}
variable "xc_p12_path" {}
variable "xc_api_url" {}
variable "swaggerfile_location" {}